services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mvp2442
      MYSQL_DATABASE: mvpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 2442
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
    - db_data:/var/lib/mysql-mvp
    command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci

  spring_app:
    image: mvp-project:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mvpdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 2442
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: